version: '3'

services:

    carteira_database:
        image: mysql:8.0
        restart: always
        ports:
            - 3306:3306
        env_file:
            - carteira_database.env
            
    carteira_app:
        build: .
        restart: always
        ports:
            - 8080:8080
        env_file:
            - carteira_app.env